import { createClient } from "@/lib/supabase/server";
import { redirect } from "next/navigation";
import Link from "next/link";
import { formatDate, formatDuration, getCallStatusColor } from "@/lib/utils";

export default async function CallsPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/auth/login");

  const { data: profile } = await supabase.from("profiles").select("dealership_id").eq("id", user.id).single();
  const dealershipId = profile?.dealership_id;
  if (!dealershipId) redirect("/dashboard");

  const { data: calls } = await supabase
    .from("calls")
    .select("*, leads(name, phone, vehicle, lead_temperature)")
    .eq("dealership_id", dealershipId)
    .order("created_at", { ascending: false });

  const stats = {
    total: calls?.length ?? 0,
    completed: calls?.filter((c) => c.status === "completed").length ?? 0,
    noAnswer: calls?.filter((c) => c.status === "no_answer").length ?? 0,
    avgDuration: calls?.length
      ? Math.round((calls.reduce((a, c) => a + (c.duration ?? 0), 0) / calls.length))
      : 0,
  };

  return (
    <div className="max-w-6xl space-y-5">
      <div>
        <h1 className="text-2xl font-bold text-slate-900">Call History</h1>
        <p className="text-slate-500 text-sm mt-0.5">All recorded calls and their outcomes</p>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {[
          { label: "Total Calls", value: stats.total },
          { label: "Completed", value: stats.completed },
          { label: "No Answer", value: stats.noAnswer },
          { label: "Avg Duration", value: formatDuration(stats.avgDuration) },
        ].map(({ label, value }) => (
          <div key={label} className="card p-4 text-center">
            <p className="text-2xl font-bold text-slate-900">{value}</p>
            <p className="text-xs text-slate-500 mt-0.5">{label}</p>
          </div>
        ))}
      </div>

      {/* Table */}
      <div className="card overflow-hidden">
        {!calls || calls.length === 0 ? (
          <div className="p-12 text-center">
            <p className="text-slate-500 font-medium">No calls recorded yet</p>
            <p className="text-slate-400 text-sm mt-1">Calls will appear here after you start calling from the queue</p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-slate-50 border-b border-slate-200">
                <tr>
                  <th className="table-header">Lead</th>
                  <th className="table-header">Phone</th>
                  <th className="table-header">Date</th>
                  <th className="table-header">Duration</th>
                  <th className="table-header">Status</th>
                  <th className="table-header">Summary</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {calls.map((call) => (
                  <tr key={call.id} className="hover:bg-slate-200 transition-colors">
                    <td className="table-cell">
                      <Link href={`/dashboard/leads/${call.lead_id}`} className="font-medium text-brand-600 hover:underline">
                        {call.leads?.name ?? "Unknown"}
                      </Link>
                      <p className="text-xs text-slate-400">{call.leads?.vehicle ?? ""}</p>
                    </td>
                    <td className="table-cell text-slate-600">{call.leads?.phone ?? "—"}</td>
                    <td className="table-cell text-slate-600">{formatDate(call.created_at)}</td>
                    <td className="table-cell text-slate-600">{call.duration > 0 ? formatDuration(call.duration) : "—"}</td>
                    <td className="table-cell">
                      <span className={`badge ${getCallStatusColor(call.status)}`}>
                        {call.status.replace(/_/g, " ")}
                      </span>
                    </td>
                    <td className="table-cell max-w-xs">
                      <p className="text-sm text-slate-600 truncate">{call.summary ?? "—"}</p>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Vapi Integration Note */}
      <div className="card p-4 bg-gradient-to-r from-purple-50 to-brand-50 border-purple-700/40">
        <p className="text-sm font-semibold text-purple-300 mb-1">🔌 Vapi AI Calling Integration Ready</p>
        <p className="text-xs text-purple-400">
          Architecture is prepared for Vapi.ai integration. When connected, calls will be placed automatically, 
          transcripts captured in real-time, and summaries generated by AI.
        </p>
      </div>
    </div>
  );
}
