import type { KnowledgeSeedEntry } from "./marketingKnowledgeSeed";

// Gap-fill batch from the 2026-08-11 RAG knowledge base audit:
// case studies were all large/funded brands (Nykaa, Meesho, CRED...)
// with nothing at the actual scale of Hawlai's users, objection
// handling was missing several common Indian small-business
// scenarios, and there was no WhatsApp-specific metrics entry
// despite WhatsApp being the most-covered channel elsewhere.
//
// The 5 case studies are explicitly framed as composite/illustrative
// patterns typical of businesses at this scale, not specific named
// companies — real financial/growth data for small private
// businesses isn't publicly verifiable the way it is for the large
// brands in marketingKnowledgeSeed2.ts, so these are honestly
// labeled as such rather than presented as verified case studies.
export const MARKETING_KNOWLEDGE_SEED_7: KnowledgeSeedEntry[] = [
  {
    category: "case_study",
    title: "A small home-décor D2C brand's Instagram-only growth pattern (illustrative, ₹50L-1.5Cr scale)",
    content: `Situation: Illustrative pattern for a small D2C brand (home décor, candles, jewelry, similar low-consideration lifestyle products) in the roughly ₹50L-1.5Cr/year revenue range, growing almost entirely through organic + light paid Instagram activity rather than a large ad budget — a composite pattern typical of this segment, not a specific verified company (real financial data for small private businesses generally isn't public).
Strategy: Growth centered on consistent Reels (3-5/week) showing the product being made/used/styled rather than polished catalog shots, paired with a simple DM-to-WhatsApp-to-checkout flow — every Reel's caption or pinned comment pushed viewers to WhatsApp rather than a website, since WhatsApp converts warm interest faster for a small catalog. Paid spend, when used, was small and entirely retargeting on people who'd already engaged (profile visitors, video viewers), not cold prospecting.
Why it works (India): For a small catalog and modest budget, organic Reels reach can rival or exceed what a small ad budget buys directly — and routing warm interest into WhatsApp (rather than a cart-abandonment-prone website checkout) matches how Indian buyers actually prefer to complete a purchase from a small, unfamiliar brand: with a real person answering questions before paying.
How to apply: If Instagram is the primary channel and budget is limited, prioritize posting consistency and a frictionless DM-to-WhatsApp path over spending on cold-audience ads — cold ads on a tiny budget rarely get enough volume to optimize well, while consistent organic content compounds.
Expected Metrics: Not a specific verified number — directionally, small brands following this pattern often report that a large majority (loosely 60-80%) of orders originate from Instagram-to-WhatsApp conversations rather than a website checkout at this scale; treat this as a rough expectation to compare your own channel-attribution split against, not a guarantee.
Common Mistakes: Spending the whole limited ad budget on cold prospecting instead of retargeting warm engagers; sending Instagram traffic to a generic website instead of a fast DM/WhatsApp reply; posting inconsistently (bursts of activity, then silence), which resets any algorithmic momentum Reels reach depends on.`,
  },
  {
    category: "case_study",
    title: "A local interior-design/renovation service's WhatsApp-inbound lead pattern (illustrative, ₹60L-2Cr scale)",
    content: `Situation: Illustrative pattern for a local considered-purchase service business (interior design, renovation, event planning, similar) in the roughly ₹60L-2Cr/year range, where the majority of new leads arrive as inbound WhatsApp messages rather than filled web forms — a composite pattern typical of this segment, not a specific verified company.
Strategy: The business treated WhatsApp as its actual sales pipeline, not just a chat tool — every inquiry got a fast (same-day) first reply with 2-3 real project photos relevant to what was asked, a rough starting price range up front (not "contact us for pricing"), and a specific next step (a site visit or call, with a date offered, not left open-ended). Past client photos and short video testimonials were saved as a ready WhatsApp catalog to send instantly rather than searched for each time.
Why it works (India): For a considered, trust-heavy local service, speed of first response and a concrete (not vague) price range are large real drivers of whether a lead proceeds — Indian buyers messaging multiple providers at once commonly go with whoever responds fastest with real specifics, not necessarily the cheapest or most polished.
How to apply: Build a ready WhatsApp "kit" in advance — a short intro message, 5-10 best project photos/testimonials organized by project type, and a rough price-range script for the most common inquiry types — so first response time stays fast without needing to improvise each time.
Expected Metrics: Not a specific verified number — directionally, local service businesses commonly report that lead-to-consultation conversion drops off sharply when first response time exceeds a few hours; track your own first-response-time versus conversion rate as the real internal benchmark.
Common Mistakes: Making inquiries wait hours or until "someone's free" to reply, losing leads to faster-responding competitors; refusing to give even a rough price range, which reads as evasive rather than premium; treating every WhatsApp inquiry as unique instead of building reusable, fast-to-send assets for common questions.`,
  },
  {
    category: "case_study",
    title: "A Tier-2 city retail/sweet shop brand's hyperlocal growth pattern (illustrative, ₹50L-1Cr scale)",
    content: `Situation: Illustrative pattern for a Tier-2 city retail business (a sweet shop, a local clothing store, a similar neighborhood-anchored business) in the roughly ₹50L-1Cr/year range, growing through hyperlocal tactics rather than city-wide or online-first marketing — a composite pattern typical of this segment, not a specific verified company.
Strategy: Marketing effort concentrated within a genuinely small radius (a few kilometers, or specific nearby neighborhoods/societies) rather than spreading thin across the whole city — WhatsApp broadcast groups organized by locality, local Google Business Profile optimization with real photos and prompt review responses, small partnerships with 2-3 nearby complementary businesses (cross-promotion, referral), and physical local touches (a flyer with a nearby society's watchman/office, a stall at a local event) that a purely digital-only strategy would skip.
Why it works (India): In Tier-2 cities, word-of-mouth and physical local presence often carry more weight relative to paid digital reach than they do in metro markets — concentrating limited budget and effort on being unmistakably present and known within a small radius tends to outperform spreading the same budget thinly across a citywide digital campaign.
How to apply: Before running any citywide or broad digital campaign, map the realistic radius most actual customers come from (often smaller than assumed) and concentrate marketing effort — WhatsApp groups, local partnerships, GBP, local events — specifically within that radius first.
Expected Metrics: Not a specific verified number — directionally, hyperlocal-focused small businesses in Tier 2/3 cities commonly report that a large share of new customers originate within a few kilometers of the physical location, coming primarily through word-of-mouth/local referral rather than paid digital ads; track your own customers' locality data (pin codes, delivery areas) to confirm this for your specific business.
Common Mistakes: Running citywide paid campaigns with a budget too thin to make an impact anywhere, instead of concentrating on a smaller radius; neglecting Google Business Profile and local reviews in favor of only Instagram/Facebook; treating local partnerships and physical local presence as unnecessary in favor of purely digital tactics.`,
  },
  {
    category: "case_study",
    title: "A solo-founder skincare/D2C brand's trust-first, review-led repeat-purchase pattern (illustrative)",
    content: `Situation: Illustrative pattern for a solo or small-team D2C brand in a trust-sensitive category (skincare, wellness, food) at an early/small scale, where the founder is also the face of the brand and repeat purchase — not one-time discovery sales — drives most revenue — a composite pattern typical of this segment, not a specific verified company.
Strategy: The founder posted personally (not just polished product content) about the "why" behind the brand and ingredient/process transparency, and responded to comments/DMs personally in the early stage rather than delegating to a generic brand voice. Every buyer was asked for a short review or photo after using the product for a set period (not immediately after purchase), and genuine reviews — including honest ones with minor caveats — were shared rather than only 5-star ones, which read as more credible.
Why it works (India): For trust-sensitive, ingestible/skin-contact categories, a visible real founder and unfiltered social proof reduce the specific fear a new, unfamiliar brand faces ("is this actually safe/genuine?") more effectively than polished but anonymous brand messaging — buyers commonly cite trusting a real person and real reviews over brand claims in these categories.
How to apply: If the founder is comfortable being visible, build a habit of occasional personal (not just branded) posts, and set up a simple, timed system to request reviews from buyers after enough time has passed to have a real opinion, rather than immediately at checkout.
Expected Metrics: Not a specific verified number — directionally, trust-sensitive small brands following this pattern commonly find repeat-purchase rate matters more to overall revenue than first-time acquisition volume at this scale; track your own repeat-purchase rate over time as the metric that actually reflects whether trust is compounding.
Common Mistakes: Keeping the founder entirely invisible and using only generic brand-voice content in a category where personal trust matters; only showcasing perfect 5-star reviews, which can read as curated/fake rather than credible; asking for reviews immediately at purchase before the buyer has had real time to form an opinion.`,
  },
  {
    category: "case_study",
    title: "A small service business's post-sale follow-up fix that recovered stalled growth (illustrative)",
    content: `Situation: Illustrative pattern for a small service business (salon, coaching, repair/maintenance service) whose new-customer acquisition was healthy but overall growth had stalled — traced back to weak post-sale follow-up and low repeat/referral rate rather than a lead-generation problem — a composite pattern typical of this segment, not a specific verified company.
Strategy: Rather than increasing ad spend to bring in more new customers, the business fixed what happened after the first purchase — a simple thank-you message within a day, a check-in message at a sensible interval for that service (e.g. before the next expected need), and a direct, specific ask for a referral or review at the moment satisfaction was highest (right after a good outcome, not weeks later).
Why it works (India): Acquiring a new customer is almost always more expensive than retaining or getting a referral from an existing one — a business with a genuine lead-gen or acquisition problem is sometimes actually solving the wrong problem, when the real gap is post-sale follow-through that would have compounded existing customers into repeat visits and referrals for near-zero additional cost.
How to apply: Before increasing acquisition spend, audit how systematically post-sale follow-up currently happens (or doesn't) — if there's no consistent thank-you, check-in, or referral-ask system, fixing that first is often cheaper and more effective than spending more to fill a leaky bucket.
Expected Metrics: Not a specific verified number — directionally, service businesses that introduce a systematic post-sale follow-up commonly report meaningful improvement in repeat-visit rate and referral volume without any increase in ad spend; track repeat-customer rate and referral-sourced new customers before and after introducing a follow-up system as the real internal benchmark.
Common Mistakes: Responding to a growth plateau by increasing acquisition spend without first checking whether retention/referral is the actual weak point; asking for referrals or reviews at a generic time rather than right after a moment of high satisfaction; having no follow-up system at all beyond the initial sale.`,
  },
  {
    category: "objection_handling",
    title: `Handling "maine kahin aur sasta dekha" (I found it cheaper elsewhere)`,
    content: `Situation: Use when a customer names a specific cheaper price they've seen elsewhere (a competitor, a marketplace listing, an unbranded alternative) — distinct from a general "mehnga hai" (too expensive) objection because here the customer has a concrete comparison point, not just general price hesitation.
Strategy: Don't immediately match or beat the quoted price — first find out specifically what the cheaper option actually is (same product/service, same quality tier, same guarantees/support?) since "cheaper" often isn't actually comparable once specifics are known. Name the real, specific differences (materials, warranty, support, genuineness) rather than vague "we're better" claims. If the comparison is genuinely apples-to-apples and matching isn't possible, it's acceptable to honestly say so rather than pretending otherwise — offer a smaller-commitment option instead of matching an unsustainable price.
Why it works (India): Indian buyers frequently price-compare across multiple sources before buying, and simply matching every quoted lower price both erodes margin and signals the original price wasn't honest — clearly naming real, specific differences lets the customer make an informed choice instead of a purely price-driven one, and often resolves the objection without any discount at all once the comparison isn't actually equal.
How to apply: Prepare a specific, factual comparison sheet in advance for the 2-3 most commonly cited cheaper alternatives/competitors, so the response is confident and concrete in the moment instead of defensive or improvised.
Expected Metrics: Not directly quotable; the relevant internal signal is conversion rate on price-comparison objections handled with a specific, factual difference-explanation versus simply matching the quoted price — track both to see which approach actually converts better without eroding margin for your specific business.
Common Mistakes: Immediately matching or beating the quoted price without first checking whether the comparison is genuinely apples-to-apples; getting defensive or dismissive about the competitor instead of factually explaining real differences; having no prepared comparison information ready, leading to a vague, unconvincing response in the moment.`,
  },
  {
    category: "objection_handling",
    title: "Handling refund and return requests without losing the customer",
    content: `Situation: Use when a customer requests a refund or return — a moment that, handled well, can retain a customer despite the issue, and handled poorly, guarantees losing them plus a likely negative public review.
Strategy: Respond quickly and without making the customer justify themselves extensively or feel like they're being accused of lying. State the actual return/refund policy clearly and simply (what's needed, how long it takes) rather than making the process feel adversarial or deliberately confusing. Where the policy allows discretion, err toward resolving quickly for a first-time or clearly genuine request — the cost of one refund is almost always smaller than the cost of a public negative review or lost future referrals from that customer's network. Follow up after the resolution to check the customer's overall sentiment, not just close the ticket.
Why it works (India): How a refund is handled is disproportionately visible — Indian buyers frequently check reviews specifically for how a business handles problems, not just whether products are good, since a business's response to something going wrong is a strong proxy for whether it's trustworthy generally.
How to apply: Write down the actual refund/return policy in plain language in advance (not just legal terms) so it can be shared instantly and consistently, and set an internal standard for how quickly refund requests should get a first response (e.g. same day) regardless of how busy the team is.
Expected Metrics: Not directly quotable; the relevant signal is whether refunded customers still leave neutral/positive reviews or return for a future purchase — a well-handled refund process commonly retains a meaningful share of otherwise-lost customers, though the exact rate varies by category and how the issue is resolved.
Common Mistakes: Making the customer repeatedly justify or prove their request before it's even considered, which reads as adversarial; slow or inconsistent responses that leave the customer anxious and more likely to escalate publicly; treating a refund purely as a loss to minimize rather than an opportunity to retain trust despite the issue.`,
  },
  {
    category: "objection_handling",
    title: "Addressing delivery time and COD trust objections",
    content: `Situation: Use when a customer hesitates specifically around delivery timing ("kitne din mein aayega," worried about delays) or around Cash on Delivery trust concerns (whether the order will actually arrive, whether COD is genuinely available) — common, distinct friction points from general price or product objections.
Strategy: Give a specific, realistic delivery window rather than a vague "jaldi mil jayega" — and if delays are possible (festival season, remote pin codes), say so upfront rather than letting the customer discover it after ordering, which damages trust far more than an honest heads-up would. For COD trust concerns, be explicit and specific about COD availability, any COD-specific charges, and what happens if the customer isn't home — proactively, not only when asked. Where possible, offer order tracking/updates so the customer isn't left wondering.
Why it works (India): Delivery reliability and COD availability are still meaningfully bigger trust factors for many Indian buyers, especially for newer or unfamiliar online/small brands, than they are in markets with longer-established e-commerce trust — being specific and proactive about both directly addresses the actual underlying fear ("will this really show up, and can I pay safely") rather than leaving it for the customer to worry about unprompted.
How to apply: Build a short, ready script covering realistic delivery timelines (including honest caveats for remote areas/peak season) and COD specifics, and volunteer this information proactively in the sales conversation rather than waiting to be asked.
Expected Metrics: Not directly quotable; the relevant signal is cart/order abandonment rate specifically at the delivery-timing or payment-method step — proactively addressing both upfront commonly reduces last-minute drop-off compared to leaving the customer to ask or assume.
Common Mistakes: Giving vague or overly optimistic delivery estimates that create disappointment later; not mentioning COD availability or its specifics unless directly asked, leaving a hesitant customer to assume the worst; failing to proactively flag realistic delays (festival season, remote areas) that then feel like broken promises after the fact.`,
  },
  {
    category: "objection_handling",
    title: "Responding when a customer directly compares you to a named competitor",
    content: `Situation: Use when a customer explicitly names a specific competitor and asks why they should choose this business instead — different from a generic price objection because the customer has already done real comparison research and is asking for a direct, honest answer.
Strategy: Never criticize or badmouth the named competitor directly — it reads as insecure and unprofessional regardless of how the criticism is delivered. Instead, answer with specific, factual points about what this business genuinely does well or differently (not vague superiority claims), and it's fine to acknowledge that the competitor may also be a reasonable choice for some needs while being specific about why this business fits this particular customer's situation. If genuinely uncertain how the business compares on a specific point, it's better to say so honestly than to overclaim.
Why it works (India): Openly badmouthing a named competitor is a common failure pattern that damages credibility more than it helps — buyers doing direct comparisons are often close to a decision and respond better to confident, specific, honest positioning than to defensive or negative comparison, since negativity itself reads as a lack of confidence in one's own offering.
How to apply: Prepare specific, factual (not vague) points of genuine differentiation for the 2-3 most commonly named competitors in advance, so responses in the moment are confident and specific rather than defensive or improvised.
Expected Metrics: Not directly quotable; the relevant internal signal is conversion rate on conversations where a named competitor comparison came up, comparing a confident/specific-differentiation response against a defensive or dismissive one for the same scenario.
Common Mistakes: Criticizing or badmouthing the named competitor, which reads as insecure regardless of accuracy; responding with vague "we're just better" claims with no specifics; refusing to acknowledge any merit in the competitor at all, which can read as dishonest to a customer who's already done real research.`,
  },
  {
    category: "metrics",
    title: "WhatsApp-specific metrics — read rate and reply rate benchmarks for India",
    content: `Situation: Use when trying to gauge whether WhatsApp marketing/sales activity (broadcasts, one-to-one follow-up, catalog sharing) is actually performing, since WhatsApp doesn't expose the same standardized analytics dashboards as email or paid ad platforms.
Strategy: Track a small set of proxies manually or via a CRM/broadcast tool: read rate (blue-tick/seen rate on messages, where visible), reply rate (percentage of contacts who respond at all, not just react), and time-to-first-reply on inbound inquiries. Segment these by list type (Hot/Warm/Cold, from prior segmentation practice) rather than looking at one blended number, since a blended average across very different segments hides what's actually happening in each.
Why it works (India): WhatsApp is a high-trust, high-attention channel in India relative to email — read rates are typically far higher than email open rates, which makes reply rate (not just read rate) the more meaningful signal of actual engagement, since a message can be seen without prompting any real interest.
How to apply: Set up a simple recurring tracking habit — even a basic spreadsheet noting messages sent, read (where visible), and replied to, per broadcast/segment — rather than relying on gut feel about whether WhatsApp activity is working.
Expected Metrics: Directional, not verified for any specific business or category: WhatsApp broadcast read rates are commonly reported in the 70-90%+ range in general small-business practice (materially higher than typical email open rates), while reply rates vary far more widely by segment — commonly cited loosely in the 10-30% range for warm/engaged segments and considerably lower for cold/inactive ones. These are rough expectations to compare your own numbers against, not guarantees, since actual rates vary significantly by list quality, message relevance, and segment recency.
Common Mistakes: Only tracking whether messages were sent, with no visibility into read or reply rates at all; looking at one blended rate across all contacts instead of segmenting by recency/engagement, which hides real segment-level performance; treating a high read rate alone as success without checking whether it's translating into actual replies or conversions.`,
  },
];
