import { createClient } from "@/lib/supabase/server";
import { redirect } from "next/navigation";
import Link from "next/link";
import { Palette, Lock } from "lucide-react";
import { getDealershipPlanLimits, hasFeature, GATED_FEATURE_MIN_PLAN, PLAN_LABELS } from "@/lib/plans";
import AgencyBrandingForm from "@/components/agency/AgencyBrandingForm";
import { buttonClasses } from "@/components/ui/Button";

// Master audit Part E3 — lets an agency replace Hawlai's own branding
// (purple accent + "Generated by Hawlai" footer) on client-facing
// reports with their own, across every business they manage. Reuses
// the multiBusiness (Agency-tier) gate rather than adding a new
// plan_limits column for what's the same tier boundary.
export default async function AgencyBrandingPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/auth/login");

  const { data: profile } = await supabase.from("profiles").select("dealership_id").eq("id", user.id).single();
  const dealershipId = profile?.dealership_id;
  if (!dealershipId) redirect("/dashboard");

  const limits = await getDealershipPlanLimits(supabase, dealershipId);
  const allowed = hasFeature(limits, "multiBusiness");

  if (!allowed) {
    return (
      <div className="max-w-lg mx-auto">
        <div className="card p-6 text-center space-y-3">
          <div className="w-10 h-10 bg-brand-500/10 rounded-xl flex items-center justify-center mx-auto">
            <Lock className="w-5 h-5 text-brand-500" />
          </div>
          <h1 className="text-lg font-bold text-slate-900">Agency Branding</h1>
          <p className="text-sm text-slate-500">
            Replace Hawlai&apos;s branding on client-facing reports (PDF, presentation, shareable link) with your own agency&apos;s logo and colors. Needs the {PLAN_LABELS[GATED_FEATURE_MIN_PLAN.multiBusiness]} plan.
          </p>
          <Link href="/dashboard/billing" className={buttonClasses("primary", "md", "inline-flex")}>Upgrade</Link>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-lg mx-auto space-y-6">
      <div className="flex items-center gap-3">
        <div className="w-10 h-10 bg-brand-500/20 rounded-xl flex items-center justify-center">
          <Palette className="w-5 h-5 text-brand-500" />
        </div>
        <div>
          <h1 className="text-xl font-bold text-slate-900">Agency Branding</h1>
          <p className="text-sm text-slate-500">White-label reports across every business you manage</p>
        </div>
      </div>

      <AgencyBrandingForm />
    </div>
  );
}
