import { createClient } from "@/lib/supabase/server";
import { NextResponse } from "next/server";
import { generateExecutiveReport } from "@/lib/agents/reportingAgent";
import { generateGrowthReport } from "@/lib/agents/growthAdvisorAgent";
import { formatCurrency } from "@/lib/utils";
import PDFDocument from "pdfkit";

export async function GET() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { data: profile } = await supabase.from("profiles").select("dealership_id").eq("id", user.id).single();
  const dealershipId = profile?.dealership_id;
  if (!dealershipId) return NextResponse.json({ error: "No dealership" }, { status: 400 });

  const { data: dealership } = await supabase.from("dealerships").select("dealership_name, business_category").eq("id", dealershipId).single();
  const [report, growth] = await Promise.all([
    generateExecutiveReport(supabase, dealershipId),
    generateGrowthReport(supabase, dealershipId, dealership?.business_category ?? "business"),
  ]);
  const { stats } = report;

  const doc = new PDFDocument({ margin: 50 });
  const chunks: Buffer[] = [];
  doc.on("data", (chunk) => chunks.push(chunk));

  const done = new Promise<Buffer>((resolve) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
  });

  const name = dealership?.dealership_name ?? "Business";
  doc.fontSize(22).text(`${name} — Performance Report`, { align: "left" });
  doc.fontSize(10).fillColor("#666").text(new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" }));
  doc.moveDown(1.5);

  doc.fillColor("#000").fontSize(14).text("Health Score", { continued: true }).fontSize(14).fillColor("#7c3aed").text(`  ${growth.healthScore}/100`);
  doc.fontSize(10).fillColor("#333").text(growth.headline);
  doc.moveDown(1);

  doc.fontSize(14).fillColor("#000").text("Key Metrics");
  doc.moveDown(0.3);
  const metrics: [string, string][] = [
    ["Total Leads", String(stats.totalLeads)],
    ["Campaigns Launched", String(stats.campaignsLaunched)],
    ["Total Ad Spend", formatCurrency(stats.totalSpend)],
    ["Cost per Lead", stats.costPerLead !== null ? formatCurrency(stats.costPerLead) : "—"],
    ["Revenue", formatCurrency(stats.totalRevenue)],
    ["ROAS", stats.roas !== null ? `${stats.roas.toFixed(1)}x` : "—"],
    ["Appointments Completed", String(stats.appointmentsCompleted)],
  ];
  for (const [label, value] of metrics) {
    doc.fontSize(10).fillColor("#333").text(label, { continued: true, width: 250 });
    doc.fillColor("#000").text(`  ${value}`);
  }
  doc.moveDown(1);

  if (growth.strengths?.length) {
    doc.fontSize(14).fillColor("#000").text("Strengths");
    growth.strengths.forEach((s: string) => doc.fontSize(10).fillColor("#333").text(`• ${s}`));
    doc.moveDown(0.8);
  }
  if (growth.risks?.length) {
    doc.fontSize(14).fillColor("#000").text("Risks");
    growth.risks.forEach((r: string) => doc.fontSize(10).fillColor("#333").text(`• ${r}`));
    doc.moveDown(0.8);
  }
  if (growth.nextActions?.length) {
    doc.fontSize(14).fillColor("#000").text("Next Actions");
    growth.nextActions.forEach((a: string) => doc.fontSize(10).fillColor("#333").text(`• ${a}`));
  }

  doc.moveDown(2);
  doc.fontSize(8).fillColor("#999").text("Generated by Hawlai", { align: "center" });

  doc.end();
  const pdfBuffer = await done;

  return new NextResponse(new Uint8Array(pdfBuffer), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${name.replace(/[^a-z0-9]+/gi, "-")}-report.pdf"`,
    },
  });
}
