// ------------------------------------------------------------------
// Agency white-labelling for client-facing reports — master audit
// Part E3.
// ------------------------------------------------------------------
// Deliberately keyed by owner_id, not dealership_id — this is the
// AGENCY's own branding, reused across every business they manage,
// not the branding of the client being reported on (that's
// brand_kits, a different, already-existing, dealership_id-scoped
// concept). Nothing changes for accounts without a row, or with the
// toggle off: getAgencyBranding() always falls back to today's
// Hawlai defaults, and hideHawlaiBranding is the single gate callers
// check before swapping any color/text/logo — an agency setting a
// logo/color without flipping the toggle sees no change, matching
// "explicit opt-in to remove Hawlai's own branding."
// ------------------------------------------------------------------

export interface AgencyBranding {
  logoUrl: string | null;
  primaryColor: string;
  agencyName: string;
  hideHawlaiBranding: boolean;
}

const DEFAULT_BRANDING: AgencyBranding = {
  logoUrl: null,
  primaryColor: "#7c3aed",
  agencyName: "Hawlai",
  hideHawlaiBranding: false,
};

export async function getAgencyBranding(supabase: any, ownerId: string | null | undefined): Promise<AgencyBranding> {
  if (!ownerId) return DEFAULT_BRANDING;
  const { data } = await supabase
    .from("agency_branding")
    .select("logo_url, primary_color, agency_name, hide_hawlai_branding")
    .eq("owner_id", ownerId)
    .maybeSingle();
  if (!data) return DEFAULT_BRANDING;
  return {
    logoUrl: data.logo_url ?? null,
    primaryColor: data.primary_color || DEFAULT_BRANDING.primaryColor,
    agencyName: data.agency_name || DEFAULT_BRANDING.agencyName,
    hideHawlaiBranding: !!data.hide_hawlai_branding,
  };
}

export function reportFooterText(branding: AgencyBranding): string {
  return branding.hideHawlaiBranding ? `Generated by ${branding.agencyName}` : "Generated by Hawlai";
}

export function reportAccentColor(branding: AgencyBranding): string {
  return branding.hideHawlaiBranding ? branding.primaryColor : DEFAULT_BRANDING.primaryColor;
}

export function reportLogoUrl(branding: AgencyBranding): string | null {
  return branding.hideHawlaiBranding ? branding.logoUrl : null;
}

// Best-effort — a broken/slow logo URL should never break report
// generation, so this swallows every failure and returns null.
export async function fetchLogoBuffer(logoUrl: string | null): Promise<{ buffer: Buffer; mimeType: string } | null> {
  if (!logoUrl) return null;
  try {
    const res = await fetch(logoUrl);
    if (!res.ok) return null;
    const arrayBuffer = await res.arrayBuffer();
    const mimeType = res.headers.get("content-type") ?? (logoUrl.endsWith(".png") ? "image/png" : "image/jpeg");
    return { buffer: Buffer.from(arrayBuffer), mimeType };
  } catch {
    return null;
  }
}
