-- ============================================================
-- Brand Kits — Brand Building page
-- ============================================================
-- Separate from brand_profiles (which holds tone/persona used to
-- steer ad/content copy). This table holds the full brand identity
-- kit: colors, typography, tagline, mission/vision, brand story,
-- social identity and personal branding guidance, plus the selected
-- logo. Generated by Claude, cached like deep_strategies so it's
-- not regenerated on every page visit — only on explicit Regenerate.

create table if not exists brand_kits (
  id uuid primary key default uuid_generate_v4(),
  dealership_id uuid references dealerships(id) on delete cascade not null unique,

  -- Full generated kit as JSON: colors, typography, tagline, mission,
  -- vision, brandStory, socialIdentity, personalBranding, guidelines.
  -- See src/lib/agents/brandBuildingAgent.ts for the exact shape.
  kit jsonb not null default '{}'::jsonb,

  -- Most recently generated/selected logo (Supabase Storage public URL).
  -- Kept as its own column since logos are generated one at a time via
  -- Gemini and re-generating the kit shouldn't wipe out a chosen logo.
  logo_url text,

  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_brand_kits_dealership_id on brand_kits(dealership_id);

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

alter table brand_kits enable row level security;

create policy "brand_kits_dealership_all" on brand_kits
  for all using (
    dealership_id in (
      select id from dealerships where owner_id = auth.uid()
    )
  );

-- ============================================================
-- Keep updated_at fresh on every edit
-- ============================================================

create or replace function public.set_brand_kits_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists on_brand_kits_update on brand_kits;
create trigger on_brand_kits_update
  before update on brand_kits
  for each row execute procedure public.set_brand_kits_updated_at();
